#!/bin/bash 
#SBATCH -J gromacs_PEP
#SBATCH -o /scratch1/06280/mcawood/benchpro/results/pending/mcawood_gromacs_PEP_2023-10-18T11-29_001N_56R_01T_00G/stdout.log
#SBATCH -e /scratch1/06280/mcawood/benchpro/results/pending/mcawood_gromacs_PEP_2023-10-18T11-29_001N_56R_01T_00G/stderr.log
#SBATCH -p debug
#SBATCH -t 01:00:00
#SBATCH -N 1
#SBATCH -n 56
#SBATCH -A A-ccsc
echo "START `date +"%Y"-%m-%dT%T` `date +"%s"`" 

echo "JobID:    ${SLURM_JOB_ID}"
echo "User:     ${USER}"
echo "Hostlist: ${SLURM_NODELIST}"

export         working_path=/scratch1/06280/mcawood/benchpro/results/pending/mcawood_gromacs_PEP_2023-10-18T11-29_001N_56R_01T_00G
export          output_file=md.log
export             mpi_exec=ibrun 
export          base_module=/scratch1/06280/mcawood/benchpro/apps/modulefiles
export           app_module=frontera/cascadelake/intel19/impi19/gromacs/2022.1/x86
export              threads=1
export                ranks=56
export                nodes=1
export                 gpus=0

# Create working directory
mkdir -p ${working_path} && cd ${working_path}

export             template=gromacs
export          bench_label=gromacs_PEP
export              dataset=gromacs_PEP
export                steps=1000
export               output=md.log
export        collect_stats=True
export     script_additions=
export                  exe=mdrun_mpi
export                 arch=
export           local_repo=/scratch1/06280/mcawood/benchpro/repo
export               stdout=stdout.log
export               stderr=stderr.log
export      OMP_NUM_THREADS=${threads} 

# Load Modules 
ml use /scratch1/hpc_tools/benchpro-dev/modulefiles 
ml use ${base_module} 
ml benchpro 
ml ${app_module} 
ml 

# [files]
stage https://portals-api.tacc.utexas.edu/postits/v2/1528b01e-181d-4d01-81ba-b1336132b518-010


#-------USER SECTION------
${mpi_exec} ${exe} -noconfout -s ./${dataset}.tpr -deffnm md -g ${output} -nsteps ${steps}
#-------------------------

# Provenance data collection script 
$BPS_INC/resources/scripts/stats/collect_stats $BP_RESULTS/pending/mcawood_gromacs_PEP_2023-10-18T11-29_001N_56R_01T_00G/hw_report

echo "END `date +"%Y"-%m-%dT%T` `date +"%s"`" 
